# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1487596086);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1487596206);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1493040294);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1487595966);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1493040174);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150328222441");
user_pref("browser.slowStartup.averageTime", 5342);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20150328222441");
user_pref("browser.startup.homepage_override.mstone", "37.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1493040119357");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1493040124406");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1493126524406");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1472397575550");
user_pref("datareporting.policy.firstRunTime", "1467973575669");
user_pref("datareporting.sessions.current.activeTicks", 37);
user_pref("datareporting.sessions.current.firstPaint", 4532);
user_pref("datareporting.sessions.current.main", 543);
user_pref("datareporting.sessions.current.sessionRestored", 5743);
user_pref("datareporting.sessions.current.startTime", "1493040051964");
user_pref("datareporting.sessions.current.totalTime", 223);
user_pref("datareporting.sessions.currentIndex", 15);
user_pref("datareporting.sessions.prunedIndex", 14);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 5);
user_pref("extensions.blocklist.pingCountVersion", 5);
user_pref("extensions.bootstrappedAddons", "{\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2014.07.01.beta,ubufox%40ubuntu.com:3.0,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:37.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1487596087);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150402.01");
user_pref("extensions.lastAppVersion", "37.0");
user_pref("extensions.lastPlatformVersion", "37.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"37.0\",\"st\":1429704334000,\"mt\":1427582713000}},\"app-system-share\":{\"webapps-team@lists.launchpad.net\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"e\":true,\"v\":\"3.0.2\",\"st\":1429704418000,\"mt\":1397665356000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"e\":true,\"v\":\"2014.07.01.beta\",\"st\":1429704418000,\"mt\":1404203370000},\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1429704418000,\"mt\":1420839520000}},\"app-system-local\":{\"online-accounts@lists.launchpad.net\":{\"d\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"e\":true,\"v\":\"0.5\",\"st\":1429704418000,\"mt\":1425919118000}}}");
user_pref("gecko.buildID", "20150328222441");
user_pref("gecko.mstone", "37.0");
user_pref("idle.lastDailyNotification", 1493040328);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1472397627);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.lastCheck", 1493040118);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.altsvc.enabled", false);
user_pref("network.http.altsvc.oe", false);
user_pref("network.http.atsvc.enabled", false);
user_pref("network.http.atsvc.oe", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1493040119);
user_pref("places.history.expiration.transient_current_max_pages", 96057);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 2);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1479910667);
user_pref("toolkit.startup.last_success", 1493040052);
user_pref("toolkit.telemetry.previousBuildID", "20150328222441");
